// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package zkgovv1beta1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_QueryCommitmentMerkleProofRequest            protoreflect.MessageDescriptor
	fd_QueryCommitmentMerkleProofRequest_commitment protoreflect.FieldDescriptor
)

func init() {
	file_sdk_zkgov_v1beta1_query_proto_init()
	md_QueryCommitmentMerkleProofRequest = File_sdk_zkgov_v1beta1_query_proto.Messages().ByName("QueryCommitmentMerkleProofRequest")
	fd_QueryCommitmentMerkleProofRequest_commitment = md_QueryCommitmentMerkleProofRequest.Fields().ByName("commitment")
}

var _ protoreflect.Message = (*fastReflection_QueryCommitmentMerkleProofRequest)(nil)

type fastReflection_QueryCommitmentMerkleProofRequest QueryCommitmentMerkleProofRequest

func (x *QueryCommitmentMerkleProofRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryCommitmentMerkleProofRequest)(x)
}

func (x *QueryCommitmentMerkleProofRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_sdk_zkgov_v1beta1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryCommitmentMerkleProofRequest_messageType fastReflection_QueryCommitmentMerkleProofRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryCommitmentMerkleProofRequest_messageType{}

type fastReflection_QueryCommitmentMerkleProofRequest_messageType struct{}

func (x fastReflection_QueryCommitmentMerkleProofRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryCommitmentMerkleProofRequest)(nil)
}
func (x fastReflection_QueryCommitmentMerkleProofRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryCommitmentMerkleProofRequest)
}
func (x fastReflection_QueryCommitmentMerkleProofRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryCommitmentMerkleProofRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryCommitmentMerkleProofRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryCommitmentMerkleProofRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) New() protoreflect.Message {
	return new(fastReflection_QueryCommitmentMerkleProofRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryCommitmentMerkleProofRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Commitment != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Commitment)
		if !f(fd_QueryCommitmentMerkleProofRequest_commitment, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest.commitment":
		return x.Commitment != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest.commitment":
		x.Commitment = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest.commitment":
		value := x.Commitment
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest.commitment":
		x.Commitment = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest.commitment":
		panic(fmt.Errorf("field commitment of message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest.commitment":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryCommitmentMerkleProofRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryCommitmentMerkleProofRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Commitment != 0 {
			n += 1 + runtime.Sov(uint64(x.Commitment))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryCommitmentMerkleProofRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Commitment != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Commitment))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryCommitmentMerkleProofRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryCommitmentMerkleProofRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryCommitmentMerkleProofRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
				}
				x.Commitment = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Commitment |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_QueryCommitmentMerkleProofResponse_1_list)(nil)

type _QueryCommitmentMerkleProofResponse_1_list struct {
	list *[][]byte
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfBytes((*x.list)[i])
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Bytes()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Bytes()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message QueryCommitmentMerkleProofResponse at list field MerkleProof as it is not of Message kind"))
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) NewElement() protoreflect.Value {
	var v []byte
	return protoreflect.ValueOfBytes(v)
}

func (x *_QueryCommitmentMerkleProofResponse_1_list) IsValid() bool {
	return x.list != nil
}

var (
	md_QueryCommitmentMerkleProofResponse              protoreflect.MessageDescriptor
	fd_QueryCommitmentMerkleProofResponse_merkle_proof protoreflect.FieldDescriptor
)

func init() {
	file_sdk_zkgov_v1beta1_query_proto_init()
	md_QueryCommitmentMerkleProofResponse = File_sdk_zkgov_v1beta1_query_proto.Messages().ByName("QueryCommitmentMerkleProofResponse")
	fd_QueryCommitmentMerkleProofResponse_merkle_proof = md_QueryCommitmentMerkleProofResponse.Fields().ByName("merkle_proof")
}

var _ protoreflect.Message = (*fastReflection_QueryCommitmentMerkleProofResponse)(nil)

type fastReflection_QueryCommitmentMerkleProofResponse QueryCommitmentMerkleProofResponse

func (x *QueryCommitmentMerkleProofResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryCommitmentMerkleProofResponse)(x)
}

func (x *QueryCommitmentMerkleProofResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_sdk_zkgov_v1beta1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryCommitmentMerkleProofResponse_messageType fastReflection_QueryCommitmentMerkleProofResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryCommitmentMerkleProofResponse_messageType{}

type fastReflection_QueryCommitmentMerkleProofResponse_messageType struct{}

func (x fastReflection_QueryCommitmentMerkleProofResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryCommitmentMerkleProofResponse)(nil)
}
func (x fastReflection_QueryCommitmentMerkleProofResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryCommitmentMerkleProofResponse)
}
func (x fastReflection_QueryCommitmentMerkleProofResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryCommitmentMerkleProofResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryCommitmentMerkleProofResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryCommitmentMerkleProofResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) New() protoreflect.Message {
	return new(fastReflection_QueryCommitmentMerkleProofResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryCommitmentMerkleProofResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.MerkleProof) != 0 {
		value := protoreflect.ValueOfList(&_QueryCommitmentMerkleProofResponse_1_list{list: &x.MerkleProof})
		if !f(fd_QueryCommitmentMerkleProofResponse_merkle_proof, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse.merkle_proof":
		return len(x.MerkleProof) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse.merkle_proof":
		x.MerkleProof = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse.merkle_proof":
		if len(x.MerkleProof) == 0 {
			return protoreflect.ValueOfList(&_QueryCommitmentMerkleProofResponse_1_list{})
		}
		listValue := &_QueryCommitmentMerkleProofResponse_1_list{list: &x.MerkleProof}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse.merkle_proof":
		lv := value.List()
		clv := lv.(*_QueryCommitmentMerkleProofResponse_1_list)
		x.MerkleProof = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse.merkle_proof":
		if x.MerkleProof == nil {
			x.MerkleProof = [][]byte{}
		}
		value := &_QueryCommitmentMerkleProofResponse_1_list{list: &x.MerkleProof}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse.merkle_proof":
		list := [][]byte{}
		return protoreflect.ValueOfList(&_QueryCommitmentMerkleProofResponse_1_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryCommitmentMerkleProofResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryCommitmentMerkleProofResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.MerkleProof) > 0 {
			for _, b := range x.MerkleProof {
				l = len(b)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryCommitmentMerkleProofResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.MerkleProof) > 0 {
			for iNdEx := len(x.MerkleProof) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.MerkleProof[iNdEx])
				copy(dAtA[i:], x.MerkleProof[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MerkleProof[iNdEx])))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryCommitmentMerkleProofResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryCommitmentMerkleProofResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryCommitmentMerkleProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MerkleProof", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MerkleProof = append(x.MerkleProof, make([]byte, postIndex-iNdEx))
				copy(x.MerkleProof[len(x.MerkleProof)-1], dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: sdk/zkgov/v1beta1/query.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryCommitmentMerkleProofRequest
type QueryCommitmentMerkleProofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment uint64 `protobuf:"varint,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *QueryCommitmentMerkleProofRequest) Reset() {
	*x = QueryCommitmentMerkleProofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_zkgov_v1beta1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCommitmentMerkleProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentMerkleProofRequest) ProtoMessage() {}

// Deprecated: Use QueryCommitmentMerkleProofRequest.ProtoReflect.Descriptor instead.
func (*QueryCommitmentMerkleProofRequest) Descriptor() ([]byte, []int) {
	return file_sdk_zkgov_v1beta1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryCommitmentMerkleProofRequest) GetCommitment() uint64 {
	if x != nil {
		return x.Commitment
	}
	return 0
}

// QueryCommitmentMerkleProofResponse
type QueryCommitmentMerkleProofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerkleProof [][]byte `protobuf:"bytes,1,rep,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
}

func (x *QueryCommitmentMerkleProofResponse) Reset() {
	*x = QueryCommitmentMerkleProofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_zkgov_v1beta1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCommitmentMerkleProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentMerkleProofResponse) ProtoMessage() {}

// Deprecated: Use QueryCommitmentMerkleProofResponse.ProtoReflect.Descriptor instead.
func (*QueryCommitmentMerkleProofResponse) Descriptor() ([]byte, []int) {
	return file_sdk_zkgov_v1beta1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryCommitmentMerkleProofResponse) GetMerkleProof() [][]byte {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

var File_sdk_zkgov_v1beta1_query_proto protoreflect.FileDescriptor

var file_sdk_zkgov_v1beta1_query_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x64, 0x6b, 0x2f, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x73, 0x64, 0x6b, 0x2e, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4d, 0x0a, 0x21, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x3a, 0x08, 0x88, 0xa0, 0x1f, 0x00, 0xe8, 0xa0, 0x1f, 0x00,
	0x22, 0x47, 0x0a, 0x22, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x6d, 0x65,
	0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x32, 0xac, 0x01, 0x0a, 0x05, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0xa2, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x34, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x16, 0x12, 0x14, 0x2f, 0x7a, 0x6b, 0x2d, 0x67, 0x6f, 0x76, 0x2f, 0x7b, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x7d, 0x42, 0xba, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x3b, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0xa2, 0x02, 0x03, 0x53, 0x5a, 0x58, 0xaa, 0x02, 0x11, 0x53, 0x64, 0x6b, 0x2e, 0x5a, 0x6b,
	0x67, 0x6f, 0x76, 0x2e, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xca, 0x02, 0x11, 0x53, 0x64,
	0x6b, 0x5c, 0x5a, 0x6b, 0x67, 0x6f, 0x76, 0x5c, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xe2,
	0x02, 0x1d, 0x53, 0x64, 0x6b, 0x5c, 0x5a, 0x6b, 0x67, 0x6f, 0x76, 0x5c, 0x56, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x13, 0x53, 0x64, 0x6b, 0x3a, 0x3a, 0x5a, 0x6b, 0x67, 0x6f, 0x76, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdk_zkgov_v1beta1_query_proto_rawDescOnce sync.Once
	file_sdk_zkgov_v1beta1_query_proto_rawDescData = file_sdk_zkgov_v1beta1_query_proto_rawDesc
)

func file_sdk_zkgov_v1beta1_query_proto_rawDescGZIP() []byte {
	file_sdk_zkgov_v1beta1_query_proto_rawDescOnce.Do(func() {
		file_sdk_zkgov_v1beta1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_zkgov_v1beta1_query_proto_rawDescData)
	})
	return file_sdk_zkgov_v1beta1_query_proto_rawDescData
}

var file_sdk_zkgov_v1beta1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_zkgov_v1beta1_query_proto_goTypes = []interface{}{
	(*QueryCommitmentMerkleProofRequest)(nil),  // 0: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest
	(*QueryCommitmentMerkleProofResponse)(nil), // 1: sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse
}
var file_sdk_zkgov_v1beta1_query_proto_depIdxs = []int32{
	0, // 0: sdk.zkgov.v1beta1.Query.CommitmentMerkleProof:input_type -> sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest
	1, // 1: sdk.zkgov.v1beta1.Query.CommitmentMerkleProof:output_type -> sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_zkgov_v1beta1_query_proto_init() }
func file_sdk_zkgov_v1beta1_query_proto_init() {
	if File_sdk_zkgov_v1beta1_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdk_zkgov_v1beta1_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCommitmentMerkleProofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_zkgov_v1beta1_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCommitmentMerkleProofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_zkgov_v1beta1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_zkgov_v1beta1_query_proto_goTypes,
		DependencyIndexes: file_sdk_zkgov_v1beta1_query_proto_depIdxs,
		MessageInfos:      file_sdk_zkgov_v1beta1_query_proto_msgTypes,
	}.Build()
	File_sdk_zkgov_v1beta1_query_proto = out.File
	file_sdk_zkgov_v1beta1_query_proto_rawDesc = nil
	file_sdk_zkgov_v1beta1_query_proto_goTypes = nil
	file_sdk_zkgov_v1beta1_query_proto_depIdxs = nil
}
